---
# defaults file for proxies logrotate-custom
proxies_logrotate_folder_path: '/etc/proxies'
proxies_logrotate_file_name: 'logrotate'
proxies_log_path: '/var/log/proxies'
proxies_logrotate_content: |
      '{{ proxies_log_path }}/*.log'
      {
        daily
        copytruncate
        size 200M
        maxsize 300M
        missingok
        rotate 1
        compress
        delaycompress
        notifempty
        create 0640 www-data adm
        sharedscripts
      }
