---
- name: Logrotate | Install logrotate
  package:
    name: logrotate
    state: present

- name: Creates Independent Folder
  file:
    path: '{{ folder_path }}'
    state: directory
- name: Creating Independent Logrotate Setup
  diff: no
  copy:
    dest: '{{ folder_path }}/{{ logrotate_file_name }}.conf'
    content: '{{ logrotate_content }}'
- name: Creating Cron to Exec Logrotate Setup
  cron:
    name: 'Execute Logrotate Setup'
    minute: '14'
    job: '/usr/sbin/logrotate {{ folder_path }}/{{ logrotate_file_name }}.conf --state {{ folder_path }}/logrotate-state'